# Generated by Django 3.2.12 on 2022-08-06 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievements',
            name='realizado',
        ),
        migrations.AlterField(
            model_name='achievements',
            name='contenido',
            field=models.CharField(max_length=250),
        ),
    ]
